services:
  api:
    image: rappytv/globaltagsapi:latest
    user: 1000:1000
    restart: unless-stopped
    ports:
      - 5000:5000
    volumes:
      - ./config.json:/app/config.json:ro
      - globaltags-icons:/app/icons

volumes:
  globaltags-icons: