services:
  api:
    image: rappytv/globaltagsapi:latest
    restart: unless-stopped
    user: root
    ports:
      - 5500:5500
    env_file: .env
    volumes:
      - ./config:/app/config:ro
      - globaltags-icons:/app/icons

volumes:
  globaltags-icons: