site_name: GlobalTags Documentation
repo_name: Global-Tags/API
repo_url: https://github.com/Global-Tags/API
edit_uri: https://github.com/Global-Tags/API/tree/master/docs/

nav:
  - Home: index.md
  - FAQ: faq.md
  - Implementations:
    - LabyMod Addon: implementations/labymod.md
    - Fabric Mod: implementations/fabric.md
  - API:
    - Guide: api/guide.md
    - Self hosting: api/self-hosting.md
    - Custom Auth Provider: api/custom-auth-provider.md
  - Language Wrappers:
      - Java Wrapper: wrappers/java.md
      - Typescript Wrapper: wrappers/typescript.md

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji

theme:
  name: material
  font:
    text: Roboto
    code: JetBrains Mono
  favicon: 'assets/theme/images/icon.png'
  logo: 'assets/theme/images/icon.png'
  features:
    - content.action.edit
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - navigation.expand
    - navigation.footer
    - search.share
  palette:
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      toggle:
        icon: material/weather-night
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

extra_css:
  - assets/theme/stylesheets/primary.css

extra:
  generator: false
  homepage: https://www.globaltags.xyz