export enum DocumentationCategory {
    Api = 'API',
    ApiKeys = 'API Keys',
    Applications = 'Applications',
    Bans = 'Bans',
    GiftCodes = 'Gift codes',
    Locks = 'Locks',
    Notes = 'Notes',
    Partners = 'Partners',
    Referrals = 'Referrals',
    Reports = 'Reports',
    Roles = 'Roles',
    Staff = 'Staff',
    Tags = 'Tags',
}