export enum GlobalIcon {
    None,
    Custom,
    Android,
    Apple,
    Bereal,
    Crown,
    Discord,
    Duolingo,
    Ebio,
    Epicgames,
    Gamescom,
    Github,
    Gitlab,
    Heart,
    Instagram,
    Kick,
    Labynet,
    Paypal,
    Pinterest,
    Playstation,
    Reddit,
    Snapchat,
    Soundcloud,
    Spotify,
    Star,
    Statsfm,
    Steam,
    Telegram,
    Threads,
    Tiktok,
    Twitch,
    X,
    Xbox,
    Youtube
}

export const icons = Object.keys(GlobalIcon).filter(key => isNaN(Number(key))).map((icon) => GlobalIcon[icon as keyof typeof GlobalIcon]);